version: "3.9"
services:
  database:
    container_name: sakura-mvno-db
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - .:/app
    ports:
      - "3308:3306"
  web:
    container_name: sakura-mvno
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - database

volumes:
  db_data: