default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  timeout: 5000

# development:
#   <<: *default
#   reconnect: true
#   database: <%= ENV.fetch("MYSQL_DATABASE") { "" } %>
#   username: <%= ENV.fetch("MYSQL_USER") { "" } %>
#   password: <%= ENV.fetch("MYSQL_PASSWORD") { "" } %>
#   host: localhost
#   port: 3308

development:
  <<: *default
  reconnect: true
  database: sakura_mvno_db
  username: root
  password: '@A123456'
  host: database
  # port: 3308

# test:
#   <<: *default

# staging:
#   <<: *default
#   reconnect: false
#   database: sakura_mvno_stg_db
#   username: root
#   password: 5n9HYAJv4gX4
#   host: stg-longterm-system.co9zzrojjqms.us-east-1.rds.amazonaws.com
#   port: 3306

# production:
#   <<: *default
#   reconnect: false
#   database: <%= ENV.fetch("OG_OPAPP_AWS_RDS_DATABASE") { "" } %>
#   username: <%= ENV.fetch("OG_OPAPP_AWS_RDS_USERNAME") { "" } %>
#   password: <%= ENV.fetch("OG_OPAPP_AWS_RDS_PASSWORD") { "" } %>
#   host: <%= ENV.fetch("OG_OPAPP_AWS_RDS_HOST") { "" } %>
#   port: <%= ENV.fetch("OG_OPAPP_AWS_RDS_PORT") { 3306 } %>
